apisix:
  node_listen: 
    - port: 9080              # APISIX listening port
      #    - port: 9443
      #      enable_ssl: true
      #  enable_http2: true
  enable_ipv6: false
  ssl:
    enable: true # Explicitly enables SSL functionality
    listen:
      # This list defines the ports for encrypted traffic (HTTPS).
      - port: 9443
  enable_http2: true # Enables HTTP/2 for this specific SSL port
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

discovery:
  kubernetes:
    service:
      schema: https
      host: "192.168.20.151"   # API server IP
      port: "6443"
    client:
      token_file: /etc/k8s/sa.token
      ssl_verify: true
      ssl_ca_cert: /etc/k8s/ca.crt
      server_name: "192.168.20.151"   # must match cert SAN
#      server_name: "kubernetes.default.svc"   # must match cert SAN
    default_weight: 50
    namespace_selector:
      equal: default

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"          # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30 
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
